export const TIMING = {
  COMPLETION_DELAY_MS: 2000,
  TYPING_DELAY_MIN_MS: 1000,
  TYPING_DELAY_MAX_MS: 2000,
  PANIC_PRESS_DURATION_MS: 2000,
  PANIC_UPDATE_INTERVAL_MS: 16, 
  RE_ENGAGEMENT_DELAY_MS: 2000,
  STEP_ADVANCE_DELAY_MS: 1500,
} as const
export const EXERCISE = {
  MIN_PHYSICAL_REPS: 20,
  MIN_PUSHUP_REPS: 15,
  MIN_JUMPING_JACK_REPS: 20,
  PHYSIOLOGICAL_SIGH_ROUNDS: 3,
  BREATHS_PER_ROUND: 3,
  TOTAL_BREATHS: 9,
  COLD_WATER_COUNTDOWN_SECONDS: 30,
  CONTRACT_DURATION_SECONDS: 600, 
  URGE_SURFING_DURATION_SECONDS: 90,
  REVERSE_VISUALIZATION_MIN_WORDS: 50,
  GROUNDING_SENSES_COUNT: 5,
  MATH_PROBLEMS_COUNT: 5,
  MATH_SUBTRACTION_VALUE: 7,
  MATH_START_VALUE: 100,
  REPLACEMENT_ACTIVITIES_MIN: 5,
  REPLACEMENT_ACTIVITIES_MAX: 10,
} as const
export const VALIDATION = {
  WHY_DOCUMENT_MIN_LENGTH: 10,
  WHY_DOCUMENT_MAX_LENGTH: 2000,
  REPLACEMENT_ACTIVITY_MIN_LENGTH: 2,
  REPLACEMENT_ACTIVITY_MAX_LENGTH: 100,
  PRECURSOR_EVENT_MAX_LENGTH: 500,
} as const
export const UI = {
  SIDEBAR_WIDTH_OPEN: 240,
  SIDEBAR_WIDTH_CLOSED: 64,
  SIDEBAR_WIDTH_MOBILE: 280,
  KEYBOARD_HEIGHT_THRESHOLD: 150,
  MAX_MESSAGE_WIDTH_PERCENT: 80,
} as const
export const STORAGE_KEYS = {
  ONBOARDING: 'urgease_onboarding',
  PRIVACY_MODE: 'urgease_privacy_mode',
} as const


